spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: andrey
    password: 1384

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true

